-- ============================================================
-- 免费云服务导航 · 「提交收录」数据库初始化脚本
-- 用法：Supabase 控制台 → SQL Editor → 新建查询 → 粘贴全部 → Run
-- 只需执行一次。
-- ============================================================

-- 1. 建表：收录申请
create table if not exists submissions (
  id          bigint generated by default as identity primary key,
  name        text        not null,              -- 服务名称
  category    text        not null,              -- 分类
  url         text        not null,              -- 官网链接
  description text        not null,              -- 一句话简介
  note        text,                              -- 坑/注意事项（选填）
  email       text,                              -- 联系邮箱（选填，不公开）
  status      text        not null default 'pending',  -- pending / approved / rejected
  created_at  timestamptz not null default now()
);

-- 2. 开启行级安全（RLS）
alter table submissions enable row level security;

-- 3. 唯一策略：匿名访客只能「插入」，不能读 / 改 / 删任何数据
--    （没有 select 策略 → 提交内容对外不可见，只有您在 Supabase 后台能看）
drop policy if exists "anon can submit" on submissions;
create policy "anon can submit"
  on submissions for insert
  to anon
  with check (true);

-- 4. 审核流：在 Supabase 控制台 Table Editor 里看 submissions 表，
--    把 status 改成 approved 即视为通过；页面展示由您手动同步进 index.html。
